
# theme: eleven-theme

eleven:
  date_format: "%b %d, %Y"
  logo:  "assets/logo.png" 

permalink: post/:title
url: "https://thewittekind.github.io"
title: "the wittekind"
description: "  a cooool band yeahh <br> @ aix-la-chapelle <br> <i>ab</i> MMXVII"
excerpt_separator: <!--more-->
page_excerpts: true

collections:
  examplecollection:
    output: true
    title: "archive"

plugins:
  - jekyll-last-modified-at

# Optional. The default date format, used if none is specified in the tag.
last-modified-at:
    date-format: '%d-%b-%y'
