
# theme: eleven-theme

eleven:
  date_format: "%b %d, %Y"
  logo:  "assets/logo.png" 

permalink: post/:title
url: "https://thewittekind.github.io"
title: "the wittekind"
description: "  a cooool band yeahh <br> @ aix-la-chapelle <br> depuis 20xx"
excerpt_separator: <!--more-->
page_excerpts: true

collections:
  examplecollection:
    output: true
    title: "archive"
